### ISSUE TITLE
Hot reload state changes?

### ISSUE THREAD

**Issue by Ehesp** [iam4x/isomorphic-flux-boilerplate#130]
I've tried Googling this, but to no avail so not sure if it's default functionality... however I've edited the files to show an example:

```
 # components/shared/spinner.jsx
  render() {
    const { active } = this.props;

    if (!active) {
      return null;
    }


    return (
    	<div>
    		Test
    	</div>
    );
  }
```

Now in `components/header.jsx`, I've updated the spinner state to true:

```
  state = {
    spinner: true
  }
```

Running the dev server, the "Test" text appears. Now, changing the above spinner state to false triggers the web pack rebuild.... But the text still appears. If I manually refresh the webpage, the Spinner is no longer rendered.

Apologies since I don't think this is the repo, but wasn't sure whether this is intended or not!

Cheers

**Comment by iam4x** [comment]
This is a normal behaviour, ES7 properties are included into constructor when class is instancied. Since hot-reloading doesn't create a new instance of the component this won't be possible.

https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=class%20Foobar%20%7B%0A%20%20%0A%20%20state%20%3D%20%7B%20foo%3A%20'bar'%20%7D%0A%20%20%0A%7D%0A%0Aclass%20Foobar2%20%7B%0A%20%20%0A%20%20constructor()%20%7B%0A%20%20%20%20this.state%20%3D%20%7B%20foo%3A%20'bar'%20%7D%0A%20%20%7D%0A%20%20%0A%7D

With this snippet you will see what's happening under the hood :+1:

**Comment by Ehesp** [comment]
Nice one! Just wanted to make sure I wasn't doing something wrong, and making a question on Stack would have taken ages to explain haha.

Thanks for the answer.
