### ISSUE TITLE
problem with assets/webpack

### ISSUE THREAD

**Issue by Bogdaan** [iam4x/isomorphic-flux-boilerplate#132]
After instalation i run
npm run dev
but assets uri return 404 (css, js, image), in log:
```
  koa blocked for 28ms +3ms
  <-- GET /assets/V2d-uc_.png
  <-- GET /assets/app-952ec619a660c6c07a24.js
  --> GET /assets/V2d-uc_.png 404 42ms 9b
  --> GET /assets/app-952ec619a660c6c07a24.js 404 25ms 9b
```

what am I doing wrong?

**Comment by dmitry** [comment]
You haven't changed anything?

**Comment by Bogdaan** [comment]
no, just clone and run

**Comment by Anomen** [comment]
Hi! FYI, I'm getting the same error.
Thnaks!

**Comment by Anomen** [comment]
![selection_039](https://cloud.githubusercontent.com/assets/219680/10869784/9a3934d6-8087-11e5-8ed2-95c3c7ae6b93.png)

In fact, it's because there is an eslint error, preventing the files to properly compile. To fix it, I needed to remove `"react/display-name": [2, { "acceptTranspilerName": true }],` from .eslintrc.
It might be worth fixing these errors though.

Thanks!
Kev

**Comment by Bogdaan** [comment]
thanks @Anomen - without react/display-name all works fine

**Comment by iam4x** [comment]
I though this issue was closed on eslint-plugin-react (https://github.com/yannickcr/eslint-plugin-react/issues/256)

I'll keep this open until it gets fixed from eslint-plugin-react.

**Comment by iam4x** [comment]
I've disabled react/display-name in server :+1:
