### ISSUE TITLE
Correct way of using localStorage

### ISSUE THREAD

**Issue by Ehesp** [iam4x/isomorphic-flux-boilerplate#135]
Hello,

In my stores, I'd like to persist the data to localStorage, for example:

```
class DomainsStore {

    constructor() {
        this.bindActions(this.alt.getActions('domains'));
        this.domains = localStorage.getItem('domains') || [];
    }

}
```

However, localStorage is not defined (neither is window) - not 100% why to be honest when the components have access to document(?). What's the recommended way to use storage here, use a npm library?

**Comment by iam4x** [comment]
@Ehesp You have a access to a global in your code: `process.env.BROWSER` if it exists you are in the browser and then you can use `window.localStorage.getItem / setItem`

You will have to modify app/main.js to load data into stores from the localStorage :+1:

**Comment by Ehesp** [comment]
Nice one, however that's sparked another couple of questions:

- Should the actions or stores be the ones using localStorage? In my head it would make sense the stores do this, but then other examples about show the actions using storage.

- How come I'd need to modify main.js? Wouldn't this mean all storage data is loaded on bootstrap when I might not be using it, as opposed to loading it from the store/actions in the constructor?

Cheers

**Comment by iam4x** [comment]
@Ehesp 

If you want to save specific data into localStorage and not the whole app data, I think the store should save data in localStorage after changes.

If you want to save whole app data into localStorage you should add a special component listening the FinalStore changes (https://github.com/altjs/utils/blob/master/src/makeFinalStore.js) and doing the save into localStorage. (Here's a decorator I made consuming FinalStore for example: https://gist.github.com/iam4x/385d9c15b0dcd1ae2476)

In main.js https://github.com/iam4x/isomorphic-flux-boilerplate/blob/master/app%2Fmain.js#L31 this line is loading the data sent from server rendering into the Flux stores, if you want to add data from localStorage you need to this yourself (merging or replacing).

Anyway, I don't think you should use localStorage or it will break the isomorphism since client and server wont share the same data. If it's for user preferences (like UI color of the website and you don't want to save this into user session) it can do the job :+1:

**Comment by iam4x** [comment]
I'll close this since there's no more answer.
