### ISSUE TITLE
Hosting suggestions

### ISSUE THREAD

**Issue by Torann** [iam4x/isomorphic-flux-boilerplate#2]
First off great boilerplate! Do you have any suggestions for hosting?

**Comment by iam4x** [comment]
Set up your own environment on a server,

I personally use dploy.io for automatic deployments from commits and pm2 (https://github.com/Unitech/pm2) for node monitoring / restart...

I don't have applications in production yet :(

**Comment by Torann** [comment]
Oh okay. I was just curious. I'm starting an isomorphic app soon, so I'm shopping around for a nice boilerplate.

**Comment by iam4x** [comment]
Hey @Torann 

I host an app on a virtual server from digitalocean, with pm2 for the monitoring. Here how looks my `processes.json`

```
{
  "apps": [
    {
      "name": "app",
      "script": "./server/index.js",
      "instances": 1,
      "log_date_format": "YYYY-MM-DD HH:mm Z",
      "log_file": "./logs/app.log",
      "error_file": "./logs/app-err.log",
      "out_file": "./logs/app-out.log",
      "exec_mode": "cluster_mode",
      "max_memory_restart": "500M",
      "watch": false,
      "env": {
        "NODE_ENV": "production"
      },
      "nord_args": "--max_old_space_size=300"
    }
  ]
}
```

I must use `--max_old_space_size=300` because V8 is using max memory possible, up to a 1.4-1.9 GB limit and I don't have that much. (see https://github.com/iojs/io.js/issues/856)

**Comment by Torann** [comment]
Perfect, thank you!
