### ISSUE TITLE
How to make connect props required that required an API call

### ISSUE THREAD

**Issue by donaldparker** [iam4x/isomorphic-flux-boilerplate#237]
Question - What am I doing wrong?
I'm not sure what I am doing wrong, but in the browser I have to do a setTimeout 0 on componentWillMount to get alt to make the request to the server for data. Also the render code gets a little sloppy with checking for the existence of any object that is loaded in via props.

Can someone point me in the right direction?

```javascript
/* /app/flux/stores/fbacct.js */
class FBAcct {
  constructor() {
    this.bindActions(this.alt.getActions('fbacct'));
    this.user = null;
  }
  onCurrSuccess(data) {
    if (data.user) this.user = data.user;
  }
}

export default FBAcct;
```

```javascript
/* /app/flux/actions/fbacct.js */
class FBAcct {
  constructor() {
    this.generateActions('currSuccess');
  }
  curr() {
    return (dispatch, alt) =>
      alt.resolve(async () => {
        try {
          alt.getActions('requests').start();
          const response = await alt.request({ url: '/users/current.json' });
          if (response.response.status === 200) this.currSuccess(response.user);
        } catch (error) {
          this.currUserError({ error });
        } finally {
          alt.getActions('requests').stop();
        }
      });
  }
```

```javascript
/* component that users the fb store */
import React, { Component, PropTypes } from 'react';
import connect from 'connect-alt';

const { BROWSER } = process.env;

@connect(({ fbacct: { user }, requests: { inProgress }) => ({ user, inProgress }))
class Dashboard extends Component {
  static propTypes = {
    user: PropTypes.object
  };

  /*had to do this to get the request to be called on the browser*/
  componentWillMount() {
    const { flux } = this.context;
    if (BROWSER) {
      setTimeout(() => {
        flux.getActions('fbacct').curr();
      }, 0);
    } else {
      flux.getActions('fbacct').curr();
    }
  }
  render() {
    if (this.props.inProgress || !this.props.user ) {
      return (<Loading msg='Loading user data' />);
    }
    const user = this.props.user;
    return (
      <div className='container dashboard-container'>
        Welcome { user.name }, you have { user.messages.length } new messages
      </div>
    );
  }
}
```

**Comment by jaredkotoff** [comment]
I'm not 100% but you can try `flux.getActions('fbacct').curr.defer();` 
My theory is that your component will mount and then it fires this request. While mounting the request resolves and then updates the store, which connect is listening too. So either it's not going to trigger an update because of timing or result in a `can not dispatch while dispatching` error. I could be wrong about this though. As I'm still trying to figure out a the proper way of loading data smoothly while in the app or a fresh load of the app (seems like i can only get one working perfectly at a time) 
Other tips: 
```JSX
render() {
    const { inProgress, user } = this.props;
    if (inProgress || !user ) return (<Loading msg='Loading user data' />);
    return (
    ...
```  
You might also want to checkout the [connect-alt's usecase example](https://github.com/iam4x/connect-alt#iii-use-into-your-application). This would result in this code:
```JSX
@connect('fbacct', 'requests')
...
static propTypes = {
    fbacctStore: PropTypes.shape({
        user: PropTypes.object
    },
    requestsStore: PropTypes.shape({
        inProgress: PropTypes.bool.isRequired
    })
  };
```

**Comment by iam4x** [comment]
@donaldparker You are doing nothing wrong, if you request this page from the server it will handle the request for you but won't call it again on browser rendering. 

See:
* https://github.com/iam4x/isomorphic-flux-boilerplate/blob/master/shared%2Falt-resolver.js#L9
* https://github.com/iam4x/isomorphic-flux-boilerplate/blob/master/shared%2Funiversal-render.jsx#L53-L58

It will only re-fetch the user if you change page and come back again on this one. It's an expected behaviour to don't duplicate API calls.

> Also the render code gets a little sloppy with checking for the existence of any object that is loaded in via props.

I don't get it sorry :(

**Comment by donaldparker** [comment]
Thanks for the help and feedback guys!
