### ISSUE TITLE
Memory consumption

### ISSUE THREAD

**Issue by jaulz** [iam4x/isomorphic-flux-boilerplate#3]
Unfortunately the gulpfile takes a lot of memory and thus breaks in cloud9. Any chance to modify the settings to reduce this?

**Comment by iam4x** [comment]
@jaulz I have just updated some of the gulptasks today, is it better?

You can run all taks sequantly by modifying the `gulpfile.js`, see https://github.com/OverZealous/run-sequence

Do you know which task is using lot of memory? Try to run them one by one like:

* `$ gulp images`
* `$ gulp style`
* `$ gulp webpack-dev-server`
* `$ gulp webpack:build`
* ...

And see on which one it breaks.

**Comment by iam4x** [comment]
@jaulz I'll try to push a branch without gulp tomorrow, using only webpack and loaders as tasks.

**Comment by jaulz** [comment]
Thanks for your great work! That looks really promising... 
Unfortunately I could not figure out yet which exact task consumes so much memory. In fact it is not a lot of memory but the free plan of Cloud9 only offers 500MB ;-)

**Comment by iam4x** [comment]
Hey,

I'm working on the only webpack build/dev on this branch: https://github.com/iam4x/isomorphic-flux-boilerplate/tree/drop-gulp

You can try for now:

* `$ npm install`
* `$ npm run build`
* `$ node server/index.js`

open http://localhost:3000 :)

**Comment by iam4x** [comment]
Hello @jaulz I've merged the branch for use with only webpack builds, is it better for you?

**Comment by iam4x** [comment]
Okey everything is in master, is it working for you?

**Comment by jaulz** [comment]
That looks better though I had some issues first to get it running because some node modules were not installed automatically. Don't know whether the error was on my machine or what caused it.. Thanks anyway! :)

Now I will check how to restrict the app to one port in dev mode... unfortunately Cloud9 only offers one external port. I will check whether koa-proxy will help us here.

**Comment by iam4x** [comment]
Hmmm this will be difficult, because 3 servers are running on dev mode:

* browser-sync that can be removed
* webpack-dev-server is serving the files for hot-reload
* koa-server is the base app server

You can easily drop browser-sync and with some configuration you can drop webpack-dev-server but you will have to rebuild files on changes (it takes more time, it will drive you crazy while developing)

If you find a way that suits your needs, feel free to open a PR for updating the docs with some informations about Cloud9.
