### ISSUE TITLE
Replace Alt with Fluxible?

### ISSUE THREAD

**Issue by doodledood** [iam4x/isomorphic-flux-boilerplate#38]
I have taken a look at [Fluxible](http://fluxible.io) and it seems like it would simplify many things.
http://fluxible.io/api/bringing-flux-to-the-server.html

Could potentially deprecate 'alt-resolver' all together and make the boilerplate use less code.
Will also enable a smoother transition to fully using ES6/7 throughout the app.

**Comment by iam4x** [comment]
There's https://github.com/gpbl/isomorphic500/ that is using Fluxible, I wanted an alternative because I prefer the simplicity of Alt.

But it will maybe change, the world of ReactJS/Flux is moving fast, for now I prefer sticking with Alt. And there are doing some work for async data fetching https://github.com/goatslacker/alt/issues/49

**Comment by doodledood** [comment]
I understand, great :)
