### ISSUE TITLE
Not isomorphic ...

### ISSUE THREAD

**Issue by andreijs** [iam4x/isomorphic-flux-boilerplate#90]
If you disable javascript buttons dont work etc

**Comment by jchapple** [comment]
That doesn't mean it's not isomorphic. It's pretty obvious that buttons with click handlers are not going to work with JavaScript disabled.

**Comment by fletcher91** [comment]
It's isomorphic, since the server [uses the same code](https://github.com/iam4x/isomorphic-flux-boilerplate/blob/master/server/router.jsx#L63) to render the document as what the client app uses.
 
You're confusing [isomorphicism](http://isomorphic.net/javascript) with [progressive enhancement](https://en.wikipedia.org/wiki/Progressive_enhancement) (or graceful degradation depending on your needs)

**Comment by iam4x** [comment]
https://medium.com/@mjackson/universal-javascript-4761051b7ae9
